jobs:
  include:
    - stage: test
      language: node_js
      os:
        - linux
        - windows
      node_js: "10"
      cache: yarn
      script: yarn test
    - stage: release
      language: node_js
      os: linux
      node_js: "10"
      branches:
        only:
          - master
      cache: yarn
      deploy:
        provider: script
        skip_cleanup: true
        script: ./script/deploy.sh
